name: Merge upstream branches
on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'farankhalid'
          git config --global user.email 'mohammadfarankhalid@gmail.com'

          git pull --unshallow

          git remote add upstream https://github.com/openai/whisper.git 
          git fetch upstream

          git checkout -b main origin/main
          git merge --no-edit upstream/main

          git checkout main
          git merge --no-edit upstream/main
